package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults {
    public static List<Region> a() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        b(region, "autoscaling", "autoscaling.af-south-1.amazonaws.com", false, true);
        b(region, "dynamodb", "dynamodb.af-south-1.amazonaws.com", false, true);
        b(region, "ec2", "ec2.af-south-1.amazonaws.com", false, true);
        b(region, "elasticloadbalancing", "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        b(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        b(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        b(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        b(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        b(region, "sns", "sns.af-south-1.amazonaws.com", false, true);
        b(region, "sqs", "sqs.af-south-1.amazonaws.com", false, true);
        b(region, "sts", "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        b(region2, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        String str = "autoscaling";
        b(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        String str2 = "cognito-identity";
        b(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        String str3 = "cognito-idp";
        b(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "ec2", "ec2.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        String str4 = "elasticloadbalancing";
        b(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        String str5 = "firehose";
        b(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        String str6 = "iot";
        b(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sdb", "sdb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sns", "sns.ap-northeast-1.amazonaws.com", false, true);
        String str7 = "sqs";
        b(region2, str7, "sqs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sts", "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        ArrayList arrayList2 = arrayList;
        b(region3, str, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str2, "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str3, "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        String str8 = "cognito-sync";
        b(region3, str8, "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "ec2", "ec2.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str4, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str6, "iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        String str9 = "logs";
        b(region3, str9, "logs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        String str10 = "s3";
        b(region3, str10, "s3.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "sns", "sns.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str7, "sqs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "sts", "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList2.add(region4);
        String str11 = "amazonaws.com";
        b(region4, str, "autoscaling.ap-south-1.amazonaws.com", false, true);
        b(region4, str2, "cognito-identity.ap-south-1.amazonaws.com", false, true);
        String str12 = str3;
        b(region4, str12, "cognito-idp.ap-south-1.amazonaws.com", false, true);
        b(region4, str8, "cognito-sync.ap-south-1.amazonaws.com", false, true);
        b(region4, "dynamodb", "dynamodb.ap-south-1.amazonaws.com", false, true);
        b(region4, "ec2", "ec2.ap-south-1.amazonaws.com", false, true);
        String str13 = str4;
        b(region4, str13, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        b(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        b(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        b(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        b(region4, str9, "logs.ap-south-1.amazonaws.com", false, true);
        String str14 = str9;
        String str15 = "polly";
        b(region4, str15, "polly.ap-south-1.amazonaws.com", false, true);
        b(region4, str10, "s3.ap-south-1.amazonaws.com", false, true);
        b(region4, "sns", "sns.ap-south-1.amazonaws.com", false, true);
        b(region4, str7, "sqs.ap-south-1.amazonaws.com", false, true);
        b(region4, "sts", "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", str11);
        arrayList2.add(region5);
        String str16 = str;
        String str17 = "sts";
        b(region5, str16, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        String str18 = str16;
        String str19 = str2;
        b(region5, str19, "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str12, "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str8, "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        String str20 = str8;
        String str21 = "data.iot";
        b(region5, str21, "data.iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        String str22 = "ec2";
        b(region5, str22, "ec2.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str13, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        String str23 = str13;
        String str24 = str6;
        b(region5, str24, "iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        String str25 = str14;
        b(region5, str25, "logs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str15, "polly.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str10, "s3.ap-southeast-1.amazonaws.com", false, true);
        String str26 = str10;
        b(region5, "sdb", "sdb.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "sns", "sns.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str7, "sqs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str17, "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", str11);
        arrayList2.add(region6);
        String str27 = str18;
        b(region6, str27, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str19, "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str12, "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        String str28 = str12;
        String str29 = str20;
        b(region6, str29, "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str21, "data.iot.ap-southeast-2.amazonaws.com", false, true);
        String str30 = str21;
        String str31 = "dynamodb";
        b(region6, str31, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str22, "ec2.ap-southeast-2.amazonaws.com", false, true);
        String str32 = str29;
        String str33 = str23;
        b(region6, str33, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str24, "iot.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        String str34 = str24;
        String str35 = "lambda";
        b(region6, str35, "lambda.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str25, "logs.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str15, "polly.ap-southeast-2.amazonaws.com", false, true);
        String str36 = str19;
        b(region6, str26, "s3.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "sdb", "sdb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "sns", "sns.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str7, "sqs.ap-southeast-2.amazonaws.com", false, true);
        String str37 = str17;
        b(region6, str37, "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", str11);
        arrayList2.add(region7);
        b(region7, str27, "autoscaling.ca-central-1.amazonaws.com", false, true);
        b(region7, str31, "dynamodb.ca-central-1.amazonaws.com", false, true);
        b(region7, str22, "ec2.ca-central-1.amazonaws.com", false, true);
        b(region7, str33, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        b(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        b(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        b(region7, str35, "lambda.ca-central-1.amazonaws.com", false, true);
        b(region7, str25, "logs.ca-central-1.amazonaws.com", false, true);
        b(region7, str15, "polly.ca-central-1.amazonaws.com", false, true);
        String str38 = str15;
        String str39 = str26;
        b(region7, str39, "s3.ca-central-1.amazonaws.com", false, true);
        b(region7, "sns", "sns.ca-central-1.amazonaws.com", false, true);
        b(region7, str7, "sqs.ca-central-1.amazonaws.com", false, true);
        b(region7, str37, "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", str11);
        arrayList2.add(region8);
        b(region8, str27, "autoscaling.eu-central-1.amazonaws.com", false, true);
        String str40 = str27;
        b(region8, str36, "cognito-identity.eu-central-1.amazonaws.com", false, true);
        b(region8, str28, "cognito-idp.eu-central-1.amazonaws.com", false, true);
        b(region8, str32, "cognito-sync.eu-central-1.amazonaws.com", false, true);
        String str41 = str30;
        b(region8, str41, "data.iot.eu-central-1.amazonaws.com", false, true);
        b(region8, str31, "dynamodb.eu-central-1.amazonaws.com", false, true);
        b(region8, str22, "ec2.eu-central-1.amazonaws.com", false, true);
        b(region8, str33, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        String str42 = str33;
        b(region8, str5, "firehose.eu-central-1.amazonaws.com", false, true);
        String str43 = str34;
        b(region8, str43, "iot.eu-central-1.amazonaws.com", false, true);
        b(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        b(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        b(region8, str35, "lambda.eu-central-1.amazonaws.com", false, true);
        b(region8, str25, "logs.eu-central-1.amazonaws.com", false, true);
        String str44 = str25;
        String str45 = str38;
        b(region8, str45, "polly.eu-central-1.amazonaws.com", false, true);
        b(region8, str39, "s3.eu-central-1.amazonaws.com", false, true);
        b(region8, "sns", "sns.eu-central-1.amazonaws.com", false, true);
        b(region8, str7, "sqs.eu-central-1.amazonaws.com", false, true);
        b(region8, str37, "sts.eu-central-1.amazonaws.com", false, true);
        Region region9 = new Region("eu-central-2", str11);
        arrayList2.add(region9);
        b(region9, str40, "autoscaling.eu-central-2.amazonaws.com", false, true);
        b(region9, str36, "cognito-identity.eu-central-2.amazonaws.com", false, true);
        b(region9, str28, "cognito-idp.eu-central-2.amazonaws.com", false, true);
        String str46 = str32;
        b(region9, str46, "cognito-sync.eu-central-2.amazonaws.com", false, true);
        b(region9, str41, "data.iot.eu-central-2.amazonaws.com", false, true);
        b(region9, str31, "dynamodb.eu-central-2.amazonaws.com", false, true);
        b(region9, str22, "ec2.eu-central-2.amazonaws.com", false, true);
        String str47 = str41;
        String str48 = str42;
        b(region9, str48, "elasticloadbalancing.eu-central-2.amazonaws.com", false, true);
        String str49 = str46;
        String str50 = str5;
        b(region9, str50, "firehose.eu-central-2.amazonaws.com", false, true);
        b(region9, str43, "iot.eu-central-2.amazonaws.com", false, true);
        b(region9, "kinesis", "kinesis.eu-central-2.amazonaws.com", false, true);
        b(region9, "kms", "kms.eu-central-2.amazonaws.com", false, true);
        b(region9, str35, "lambda.eu-central-2.amazonaws.com", false, true);
        String str51 = str44;
        b(region9, str51, "logs.eu-central-2.amazonaws.com", false, true);
        b(region9, str45, "polly.eu-central-2.amazonaws.com", false, true);
        b(region9, str39, "s3.eu-central-2.amazonaws.com", false, true);
        String str52 = str45;
        b(region9, "sdb", "sdb.eu-central-2.amazonaws.com", false, true);
        b(region9, "sns", "sns.eu-central-2.amazonaws.com", false, true);
        b(region9, str7, "sqs.eu-central-2.amazonaws.com", false, true);
        String str53 = str37;
        b(region9, str53, "sts.eu-central-2.amazonaws.com", false, true);
        String str54 = str11;
        Region region10 = new Region("eu-south-1", str54);
        ArrayList arrayList3 = arrayList2;
        arrayList3.add(region10);
        String str55 = "kinesis";
        String str56 = str43;
        String str57 = str50;
        String str58 = str40;
        b(region10, str58, "autoscaling.eu-south-1.amazonaws.com", false, true);
        b(region10, str31, "dynamodb.eu-south-1.amazonaws.com", false, true);
        b(region10, str22, "ec2.eu-south-1.amazonaws.com", false, true);
        b(region10, str48, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        b(region10, str35, "lambda.eu-south-1.amazonaws.com", false, true);
        b(region10, str51, "logs.eu-south-1.amazonaws.com", false, true);
        b(region10, str39, "s3.eu-south-1.amazonaws.com", false, true);
        b(region10, "sns", "sns.eu-south-1.amazonaws.com", false, true);
        b(region10, str7, "sqs.eu-south-1.amazonaws.com", false, true);
        b(region10, str53, "sts.eu-south-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-south-2", str54);
        arrayList3.add(region11);
        b(region11, str58, "autoscaling.eu-south-2.amazonaws.com", false, true);
        b(region11, str36, "cognito-identity.eu-south-2.amazonaws.com", false, true);
        b(region11, str28, "cognito-idp.eu-south-2.amazonaws.com", false, true);
        b(region11, str49, "cognito-sync.eu-south-2.amazonaws.com", false, true);
        String str59 = str47;
        b(region11, str59, "data.iot.eu-south-2.amazonaws.com", false, true);
        b(region11, str31, "dynamodb.eu-south-2.amazonaws.com", false, true);
        b(region11, str22, "ec2.eu-south-2.amazonaws.com", false, true);
        b(region11, str48, "elasticloadbalancing.eu-south-2.amazonaws.com", false, true);
        String str60 = str48;
        b(region11, str57, "firehose.eu-south-2.amazonaws.com", false, true);
        b(region11, str56, "iot.eu-south-2.amazonaws.com", false, true);
        b(region11, str55, "kinesis.eu-south-2.amazonaws.com", false, true);
        String str61 = "kms";
        b(region11, str61, "kms.eu-south-2.amazonaws.com", false, true);
        b(region11, str35, "lambda.eu-south-2.amazonaws.com", false, true);
        b(region11, str51, "logs.eu-south-2.amazonaws.com", false, true);
        String str62 = str51;
        String str63 = str52;
        b(region11, str63, "polly.eu-south-2.amazonaws.com", false, true);
        b(region11, str39, "s3.eu-south-2.amazonaws.com", false, true);
        String str64 = str39;
        b(region11, "sdb", "sdb.eu-south-2.amazonaws.com", false, true);
        b(region11, "sns", "sns.eu-south-2.amazonaws.com", false, true);
        b(region11, str7, "sqs.eu-south-2.amazonaws.com", false, true);
        b(region11, str53, "sts.eu-south-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-1", str54);
        arrayList3.add(region12);
        b(region12, str40, "autoscaling.eu-west-1.amazonaws.com", false, true);
        b(region12, str36, "cognito-identity.eu-west-1.amazonaws.com", false, true);
        b(region12, str28, "cognito-idp.eu-west-1.amazonaws.com", false, true);
        String str65 = str49;
        b(region12, str65, "cognito-sync.eu-west-1.amazonaws.com", false, true);
        b(region12, str59, "data.iot.eu-west-1.amazonaws.com", false, true);
        b(region12, str31, "dynamodb.eu-west-1.amazonaws.com", false, true);
        b(region12, str22, "ec2.eu-west-1.amazonaws.com", false, true);
        String str66 = str59;
        b(region12, str60, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        b(region12, "email", "email.eu-west-1.amazonaws.com", false, true);
        b(region12, str57, "firehose.eu-west-1.amazonaws.com", false, true);
        b(region12, str56, "iot.eu-west-1.amazonaws.com", false, true);
        String str67 = str55;
        b(region12, str67, "kinesis.eu-west-1.amazonaws.com", false, true);
        b(region12, str61, "kms.eu-west-1.amazonaws.com", false, true);
        b(region12, str35, "lambda.eu-west-1.amazonaws.com", false, true);
        String str68 = str35;
        b(region12, str62, "logs.eu-west-1.amazonaws.com", false, true);
        b(region12, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        b(region12, str63, "polly.eu-west-1.amazonaws.com", false, true);
        b(region12, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        b(region12, str64, "s3.eu-west-1.amazonaws.com", false, true);
        b(region12, "sdb", "sdb.eu-west-1.amazonaws.com", false, true);
        b(region12, "sns", "sns.eu-west-1.amazonaws.com", false, true);
        b(region12, str7, "sqs.eu-west-1.amazonaws.com", false, true);
        b(region12, str53, "sts.eu-west-1.amazonaws.com", false, true);
        Region region13 = new Region("eu-west-2", str54);
        arrayList3.add(region13);
        b(region13, str40, "autoscaling.eu-west-2.amazonaws.com", false, true);
        b(region13, str36, "cognito-identity.eu-west-2.amazonaws.com", false, true);
        String str69 = str28;
        b(region13, str69, "cognito-idp.eu-west-2.amazonaws.com", false, true);
        b(region13, str65, "cognito-sync.eu-west-2.amazonaws.com", false, true);
        b(region13, str31, "dynamodb.eu-west-2.amazonaws.com", false, true);
        b(region13, str22, "ec2.eu-west-2.amazonaws.com", false, true);
        String str70 = str65;
        String str71 = str60;
        b(region13, str71, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        String str72 = str69;
        b(region13, str56, "iot.eu-west-2.amazonaws.com", false, true);
        b(region13, str67, "kinesis.eu-west-2.amazonaws.com", false, true);
        b(region13, str61, "kms.eu-west-2.amazonaws.com", false, true);
        b(region13, str68, "lambda.eu-west-2.amazonaws.com", false, true);
        String str73 = str62;
        b(region13, str73, "logs.eu-west-2.amazonaws.com", false, true);
        b(region13, str63, "polly.eu-west-2.amazonaws.com", false, true);
        String str74 = str63;
        String str75 = str64;
        b(region13, str75, "s3.eu-west-2.amazonaws.com", false, true);
        b(region13, "sns", "sns.eu-west-2.amazonaws.com", false, true);
        b(region13, str7, "sqs.eu-west-2.amazonaws.com", false, true);
        b(region13, str53, "sts.eu-west-2.amazonaws.com", false, true);
        Region region14 = new Region("eu-west-3", str54);
        arrayList3.add(region14);
        ArrayList arrayList4 = arrayList3;
        String str76 = str40;
        b(region14, str76, "autoscaling.eu-west-3.amazonaws.com", false, true);
        b(region14, str31, "dynamodb.eu-west-3.amazonaws.com", false, true);
        b(region14, str22, "ec2.eu-west-3.amazonaws.com", false, true);
        b(region14, str71, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        b(region14, str67, "kinesis.eu-west-3.amazonaws.com", false, true);
        b(region14, str61, "kms.eu-west-3.amazonaws.com", false, true);
        String str77 = str61;
        String str78 = str68;
        b(region14, str78, "lambda.eu-west-3.amazonaws.com", false, true);
        b(region14, str73, "logs.eu-west-3.amazonaws.com", false, true);
        String str79 = str73;
        String str80 = str74;
        b(region14, str80, "polly.eu-west-3.amazonaws.com", false, true);
        b(region14, str75, "s3.eu-west-3.amazonaws.com", false, true);
        b(region14, "sns", "sns.eu-west-3.amazonaws.com", false, true);
        b(region14, str7, "sqs.eu-west-3.amazonaws.com", false, true);
        b(region14, str53, "sts.eu-west-3.amazonaws.com", false, true);
        Region region15 = new Region("sa-east-1", str54);
        arrayList4.add(region15);
        b(region15, str76, "autoscaling.sa-east-1.amazonaws.com", false, true);
        b(region15, str31, "dynamodb.sa-east-1.amazonaws.com", false, true);
        b(region15, str22, "ec2.sa-east-1.amazonaws.com", false, true);
        b(region15, str71, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        b(region15, str67, "kinesis.sa-east-1.amazonaws.com", false, true);
        String str81 = str67;
        String str82 = str77;
        b(region15, str82, "kms.sa-east-1.amazonaws.com", false, true);
        b(region15, str78, "lambda.sa-east-1.amazonaws.com", false, true);
        String str83 = str78;
        String str84 = str79;
        b(region15, str84, "logs.sa-east-1.amazonaws.com", false, true);
        b(region15, str80, "polly.sa-east-1.amazonaws.com", false, true);
        b(region15, str75, "s3.sa-east-1.amazonaws.com", false, true);
        String str85 = str75;
        b(region15, "sdb", "sdb.sa-east-1.amazonaws.com", false, true);
        b(region15, "sns", "sns.sa-east-1.amazonaws.com", false, true);
        b(region15, str7, "sqs.sa-east-1.amazonaws.com", false, true);
        b(region15, str53, "sts.sa-east-1.amazonaws.com", false, true);
        Region region16 = new Region("us-east-1", str54);
        ArrayList arrayList5 = arrayList4;
        arrayList5.add(region16);
        b(region16, str76, "autoscaling.us-east-1.amazonaws.com", false, true);
        String str86 = str76;
        b(region16, str36, "cognito-identity.us-east-1.amazonaws.com", false, true);
        b(region16, str72, "cognito-idp.us-east-1.amazonaws.com", false, true);
        b(region16, str70, "cognito-sync.us-east-1.amazonaws.com", false, true);
        b(region16, str66, "data.iot.us-east-1.amazonaws.com", false, true);
        b(region16, str31, "dynamodb.us-east-1.amazonaws.com", false, true);
        b(region16, str22, "ec2.us-east-1.amazonaws.com", false, true);
        b(region16, str71, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        b(region16, "email", "email.us-east-1.amazonaws.com", false, true);
        b(region16, str57, "firehose.us-east-1.amazonaws.com", false, true);
        b(region16, str56, "iot.us-east-1.amazonaws.com", false, true);
        String str87 = str81;
        b(region16, str87, "kinesis.us-east-1.amazonaws.com", false, true);
        b(region16, str82, "kms.us-east-1.amazonaws.com", false, true);
        String str88 = str82;
        String str89 = str83;
        b(region16, str89, "lambda.us-east-1.amazonaws.com", false, true);
        b(region16, str84, "logs.us-east-1.amazonaws.com", false, true);
        String str90 = str84;
        b(region16, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        b(region16, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        b(region16, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        b(region16, str80, "polly.us-east-1.amazonaws.com", false, true);
        b(region16, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        b(region16, str85, "s3.amazonaws.com", false, true);
        b(region16, "sdb", "sdb.amazonaws.com", false, true);
        b(region16, "sns", "sns.us-east-1.amazonaws.com", false, true);
        b(region16, str7, "sqs.us-east-1.amazonaws.com", false, true);
        b(region16, str53, "sts.us-east-1.amazonaws.com", false, true);
        Region region17 = new Region("us-east-2", str54);
        arrayList5.add(region17);
        b(region17, str86, "autoscaling.us-east-2.amazonaws.com", false, true);
        b(region17, str36, "cognito-identity.us-east-2.amazonaws.com", false, true);
        b(region17, str72, "cognito-idp.us-east-2.amazonaws.com", false, true);
        b(region17, str70, "cognito-sync.us-east-2.amazonaws.com", false, true);
        b(region17, str31, "dynamodb.us-east-2.amazonaws.com", false, true);
        b(region17, str22, "ec2.us-east-2.amazonaws.com", false, true);
        b(region17, str71, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        b(region17, str57, "firehose.us-east-2.amazonaws.com", false, true);
        b(region17, str56, "iot.us-east-2.amazonaws.com", false, true);
        b(region17, str87, "kinesis.us-east-2.amazonaws.com", false, true);
        String str91 = str88;
        b(region17, str91, "kms.us-east-2.amazonaws.com", false, true);
        b(region17, str89, "lambda.us-east-2.amazonaws.com", false, true);
        String str92 = str89;
        String str93 = str90;
        b(region17, str93, "logs.us-east-2.amazonaws.com", false, true);
        b(region17, str80, "polly.us-east-2.amazonaws.com", false, true);
        String str94 = str80;
        String str95 = str85;
        b(region17, str95, "s3.us-east-2.amazonaws.com", false, true);
        b(region17, "sns", "sns.us-east-2.amazonaws.com", false, true);
        b(region17, str7, "sqs.us-east-2.amazonaws.com", false, true);
        b(region17, str53, "sts.us-east-2.amazonaws.com", false, true);
        Region region18 = new Region("us-west-1", str54);
        arrayList5.add(region18);
        ArrayList arrayList6 = arrayList5;
        String str96 = str86;
        b(region18, str96, "autoscaling.us-west-1.amazonaws.com", false, true);
        b(region18, str31, "dynamodb.us-west-1.amazonaws.com", false, true);
        b(region18, str22, "ec2.us-west-1.amazonaws.com", false, true);
        b(region18, str71, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        b(region18, str87, "kinesis.us-west-1.amazonaws.com", false, true);
        b(region18, str91, "kms.us-west-1.amazonaws.com", false, true);
        String str97 = str91;
        String str98 = str92;
        b(region18, str98, "lambda.us-west-1.amazonaws.com", false, true);
        b(region18, str93, "logs.us-west-1.amazonaws.com", false, true);
        String str99 = str93;
        String str100 = str94;
        b(region18, str100, "polly.us-west-1.amazonaws.com", false, true);
        b(region18, str95, "s3.us-west-1.amazonaws.com", false, true);
        String str101 = str95;
        b(region18, "sdb", "sdb.us-west-1.amazonaws.com", false, true);
        b(region18, "sns", "sns.us-west-1.amazonaws.com", false, true);
        b(region18, str7, "sqs.us-west-1.amazonaws.com", false, true);
        b(region18, str53, "sts.us-west-1.amazonaws.com", false, true);
        Region region19 = new Region("us-west-2", str54);
        ArrayList arrayList7 = arrayList6;
        arrayList7.add(region19);
        b(region19, str96, "autoscaling.us-west-2.amazonaws.com", false, true);
        String str102 = str54;
        b(region19, str36, "cognito-identity.us-west-2.amazonaws.com", false, true);
        b(region19, str72, "cognito-idp.us-west-2.amazonaws.com", false, true);
        b(region19, str70, "cognito-sync.us-west-2.amazonaws.com", false, true);
        b(region19, str66, "data.iot.us-west-2.amazonaws.com", false, true);
        b(region19, str31, "dynamodb.us-west-2.amazonaws.com", false, true);
        b(region19, str22, "ec2.us-west-2.amazonaws.com", false, true);
        b(region19, str71, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        b(region19, "email", "email.us-west-2.amazonaws.com", false, true);
        b(region19, str57, "firehose.us-west-2.amazonaws.com", false, true);
        String str103 = str56;
        b(region19, str103, "iot.us-west-2.amazonaws.com", false, true);
        b(region19, str87, "kinesis.us-west-2.amazonaws.com", false, true);
        String str104 = str87;
        b(region19, str97, "kms.us-west-2.amazonaws.com", false, true);
        b(region19, str98, "lambda.us-west-2.amazonaws.com", false, true);
        String str105 = str99;
        b(region19, str105, "logs.us-west-2.amazonaws.com", false, true);
        b(region19, str100, "polly.us-west-2.amazonaws.com", false, true);
        String str106 = str100;
        b(region19, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        b(region19, str101, "s3.us-west-2.amazonaws.com", false, true);
        b(region19, "sdb", "sdb.us-west-2.amazonaws.com", false, true);
        b(region19, "sns", "sns.us-west-2.amazonaws.com", false, true);
        b(region19, str7, "sqs.us-west-2.amazonaws.com", false, true);
        b(region19, str53, "sts.us-west-2.amazonaws.com", false, true);
        Region region20 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList7.add(region20);
        b(region20, str96, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str36, "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str31, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str22, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str71, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str103, "iot.cn-north-1.amazonaws.com.cn", false, true);
        String str107 = str104;
        b(region20, str107, "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str98, "lambda.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str105, "logs.cn-north-1.amazonaws.com.cn", false, true);
        String str108 = str103;
        String str109 = str101;
        b(region20, str109, "s3.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, "sns", "sns.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str7, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        b(region20, str53, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region21 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList7.add(region21);
        b(region21, str96, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str31, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str22, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str71, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str107, "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str105, "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str109, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, "sns", "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str7, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region21, str53, "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        String str110 = str102;
        Region region22 = new Region("us-gov-west-1", str110);
        arrayList7.add(region22);
        b(region22, str96, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str31, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str22, "ec2.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str71, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str107, "kinesis.us-gov-west-1.amazonaws.com", false, true);
        String str111 = str107;
        String str112 = str97;
        b(region22, str112, "kms.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str98, "lambda.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str105, "logs.us-gov-west-1.amazonaws.com", false, true);
        String str113 = str105;
        b(region22, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str109, "s3.us-gov-west-1.amazonaws.com", false, true);
        b(region22, "sns", "sns.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str7, "sqs.us-gov-west-1.amazonaws.com", false, true);
        b(region22, str53, "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region23 = new Region("us-gov-east-1", str110);
        ArrayList arrayList8 = arrayList7;
        arrayList8.add(region23);
        b(region23, str96, "autoscaling.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str31, "dynamodb.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str22, "ec2.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str71, "elasticloadbalancing.us-gov-east-1.amazonaws.com", false, true);
        String str114 = str71;
        String str115 = str111;
        b(region23, str115, "kinesis.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str112, "kms.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str98, "lambda.us-gov-east-1.amazonaws.com", false, true);
        String str116 = str98;
        b(region23, str113, "logs.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "rekognition", "rekognition.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str109, "s3.us-gov-east-1.amazonaws.com", false, true);
        b(region23, "sns", "sns.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str7, "sqs.us-gov-east-1.amazonaws.com", false, true);
        b(region23, str53, "sts.us-gov-east-1.amazonaws.com", false, true);
        Region region24 = new Region("eu-north-1", str110);
        arrayList8.add(region24);
        b(region24, str96, "autoscaling.eu-north-1.amazonaws.com", false, true);
        b(region24, str31, "dynamodb.eu-north-1.amazonaws.com", false, true);
        b(region24, str22, "ec2.eu-north-1.amazonaws.com", false, true);
        b(region24, str114, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        b(region24, str57, "firehose.eu-north-1.amazonaws.com", false, true);
        b(region24, str108, "iot.eu-north-1.amazonaws.com", false, true);
        b(region24, str115, "kinesis.eu-north-1.amazonaws.com", false, true);
        b(region24, str112, "kms.eu-north-1.amazonaws.com", false, true);
        b(region24, str116, "lambda.eu-north-1.amazonaws.com", false, true);
        String str117 = str113;
        b(region24, str117, "logs.eu-north-1.amazonaws.com", false, true);
        b(region24, str109, "s3.eu-north-1.amazonaws.com", false, true);
        b(region24, "sns", "sns.eu-north-1.amazonaws.com", false, true);
        b(region24, str7, "sqs.eu-north-1.amazonaws.com", false, true);
        b(region24, str53, "sts.eu-north-1.amazonaws.com", false, true);
        Region region25 = new Region("ap-east-1", str110);
        arrayList8.add(region25);
        b(region25, str96, "autoscaling.ap-east-1.amazonaws.com", false, true);
        b(region25, str31, "dynamodb.ap-east-1.amazonaws.com", false, true);
        b(region25, str22, "ec2.ap-east-1.amazonaws.com", false, true);
        String str118 = str22;
        b(region25, str114, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        String str119 = str57;
        b(region25, str119, "firehose.ap-east-1.amazonaws.com", false, true);
        b(region25, str115, "kinesis.ap-east-1.amazonaws.com", false, true);
        b(region25, str112, "kms.ap-east-1.amazonaws.com", false, true);
        String str120 = str112;
        String str121 = str116;
        b(region25, str121, "lambda.ap-east-1.amazonaws.com", false, true);
        b(region25, str117, "logs.ap-east-1.amazonaws.com", false, true);
        String str122 = str117;
        String str123 = str106;
        b(region25, str123, "polly.ap-east-1.amazonaws.com", false, true);
        b(region25, str109, "s3.ap-east-1.amazonaws.com", false, true);
        b(region25, "sns", "sns.ap-east-1.amazonaws.com", false, true);
        b(region25, str7, "sqs.ap-east-1.amazonaws.com", false, true);
        b(region25, str53, "sts.ap-east-1.amazonaws.com", false, true);
        Region region26 = new Region("me-south-1", str110);
        arrayList8.add(region26);
        b(region26, str96, "autoscaling.me-south-1.amazonaws.com", false, true);
        String str124 = str96;
        b(region26, str36, "cognito-identity.me-south-1.amazonaws.com", false, true);
        b(region26, str72, "cognito-idp.me-south-1.amazonaws.com", false, true);
        b(region26, str70, "cognito-sync.me-south-1.amazonaws.com", false, true);
        String str125 = str66;
        b(region26, str125, "data.iot.me-south-1.amazonaws.com", false, true);
        b(region26, str31, "dynamodb.me-south-1.amazonaws.com", false, true);
        String str126 = str31;
        b(region26, str118, "ec2.me-south-1.amazonaws.com", false, true);
        String str127 = str114;
        b(region26, str127, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        b(region26, str119, "firehose.me-south-1.amazonaws.com", false, true);
        String str128 = str119;
        String str129 = str108;
        b(region26, str129, "iot.me-south-1.amazonaws.com", false, true);
        b(region26, str115, "kinesis.me-south-1.amazonaws.com", false, true);
        String str130 = str115;
        String str131 = str120;
        b(region26, str131, "kms.me-south-1.amazonaws.com", false, true);
        b(region26, str121, "lambda.me-south-1.amazonaws.com", false, true);
        String str132 = str121;
        String str133 = str122;
        b(region26, str133, "logs.me-south-1.amazonaws.com", false, true);
        b(region26, str123, "polly.me-south-1.amazonaws.com", false, true);
        b(region26, str109, "s3.me-south-1.amazonaws.com", false, true);
        String str134 = str109;
        b(region26, "sdb", "sdb.me-south-1.amazonaws.com", false, true);
        b(region26, "sns", "sns.me-south-1.amazonaws.com", false, true);
        b(region26, str7, "sqs.me-south-1.amazonaws.com", false, true);
        b(region26, str53, "sts.me-south-1.amazonaws.com", false, true);
        Region region27 = new Region("ap-southeast-3", str110);
        arrayList8.add(region27);
        b(region27, str124, "autoscaling.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str36, "cognito-identity.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str72, "cognito-idp.ap-southeast-3.amazonaws.com", false, true);
        String str135 = str70;
        b(region27, str135, "cognito-sync.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str125, "data.iot.ap-southeast-3.amazonaws.com", false, true);
        String str136 = str125;
        b(region27, str126, "dynamodb.ap-southeast-3.amazonaws.com", false, true);
        String str137 = str118;
        b(region27, str137, "ec2.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str127, "elasticloadbalancing.ap-southeast-3.amazonaws.com", false, true);
        String str138 = str127;
        String str139 = str128;
        b(region27, str139, "firehose.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str129, "iot.ap-southeast-3.amazonaws.com", false, true);
        String str140 = str129;
        String str141 = str130;
        b(region27, str141, "kinesis.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str131, "kms.ap-southeast-3.amazonaws.com", false, true);
        String str142 = str131;
        String str143 = str132;
        b(region27, str143, "lambda.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str133, "logs.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str123, "polly.ap-southeast-3.amazonaws.com", false, true);
        String str144 = str123;
        b(region27, str134, "s3.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "sdb", "sdb.ap-southeast-3.amazonaws.com", false, true);
        b(region27, "sns", "sns.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str7, "sqs.ap-southeast-3.amazonaws.com", false, true);
        b(region27, str53, "sts.ap-southeast-3.amazonaws.com", false, true);
        Region region28 = new Region("me-central-1", str110);
        arrayList8.add(region28);
        b(region28, str124, "autoscaling.me-central-1.amazonaws.com", false, true);
        b(region28, str36, "cognito-identity.me-central-1.amazonaws.com", false, true);
        String str145 = str72;
        b(region28, str145, "cognito-idp.me-central-1.amazonaws.com", false, true);
        b(region28, str135, "cognito-sync.me-central-1.amazonaws.com", false, true);
        String str146 = str135;
        b(region28, str136, "data.iot.me-central-1.amazonaws.com", false, true);
        String str147 = str126;
        b(region28, str147, "dynamodb.me-central-1.amazonaws.com", false, true);
        b(region28, str137, "ec2.me-central-1.amazonaws.com", false, true);
        String str148 = str137;
        String str149 = str138;
        b(region28, str149, "elasticloadbalancing.me-central-1.amazonaws.com", false, true);
        b(region28, str139, "firehose.me-central-1.amazonaws.com", false, true);
        String str150 = str139;
        String str151 = str140;
        b(region28, str151, "iot.me-central-1.amazonaws.com", false, true);
        b(region28, str141, "kinesis.me-central-1.amazonaws.com", false, true);
        String str152 = str141;
        String str153 = str142;
        b(region28, str153, "kms.me-central-1.amazonaws.com", false, true);
        b(region28, str143, "lambda.me-central-1.amazonaws.com", false, true);
        b(region28, str133, "logs.me-central-1.amazonaws.com", false, true);
        String str154 = str133;
        b(region28, str144, "polly.me-central-1.amazonaws.com", false, true);
        b(region28, str134, "s3.me-central-1.amazonaws.com", false, true);
        b(region28, "sdb", "sdb.me-central-1.amazonaws.com", false, true);
        b(region28, "sns", "sns.me-central-1.amazonaws.com", false, true);
        b(region28, str7, "sqs.me-central-1.amazonaws.com", false, true);
        b(region28, str53, "sts.me-central-1.amazonaws.com", false, true);
        Region region29 = new Region("ap-south-2", str110);
        arrayList8.add(region29);
        b(region29, str124, "autoscaling.ap-south-2.amazonaws.com", false, true);
        String str155 = str36;
        b(region29, str155, "cognito-identity.ap-south-2.amazonaws.com", false, true);
        b(region29, str145, "cognito-idp.ap-south-2.amazonaws.com", false, true);
        String str156 = str145;
        b(region29, str146, "cognito-sync.ap-south-2.amazonaws.com", false, true);
        String str157 = str136;
        b(region29, str157, "data.iot.ap-south-2.amazonaws.com", false, true);
        b(region29, str147, "dynamodb.ap-south-2.amazonaws.com", false, true);
        String str158 = str147;
        String str159 = str148;
        b(region29, str159, "ec2.ap-south-2.amazonaws.com", false, true);
        b(region29, str149, "elasticloadbalancing.ap-south-2.amazonaws.com", false, true);
        String str160 = str149;
        String str161 = str150;
        b(region29, str161, "firehose.ap-south-2.amazonaws.com", false, true);
        b(region29, str151, "iot.ap-south-2.amazonaws.com", false, true);
        String str162 = str151;
        String str163 = str152;
        b(region29, str163, "kinesis.ap-south-2.amazonaws.com", false, true);
        b(region29, str153, "kms.ap-south-2.amazonaws.com", false, true);
        b(region29, str143, "lambda.ap-south-2.amazonaws.com", false, true);
        String str164 = str143;
        b(region29, str154, "logs.ap-south-2.amazonaws.com", false, true);
        b(region29, str144, "polly.ap-south-2.amazonaws.com", false, true);
        b(region29, str134, "s3.ap-south-2.amazonaws.com", false, true);
        b(region29, "sdb", "sdb.ap-south-2.amazonaws.com", false, true);
        b(region29, "sns", "sns.ap-south-2.amazonaws.com", false, true);
        b(region29, str7, "sqs.ap-south-2.amazonaws.com", false, true);
        b(region29, str53, "sts.ap-south-2.amazonaws.com", false, true);
        Region region30 = new Region("ap-southeast-4", str110);
        arrayList8.add(region30);
        String str165 = str124;
        b(region30, str165, "autoscaling.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str155, "cognito-identity.ap-southeast-4.amazonaws.com", false, true);
        String str166 = str155;
        b(region30, str156, "cognito-idp.ap-southeast-4.amazonaws.com", false, true);
        String str167 = str146;
        b(region30, str167, "cognito-sync.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str157, "data.iot.ap-southeast-4.amazonaws.com", false, true);
        String str168 = str157;
        String str169 = str158;
        b(region30, str169, "dynamodb.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str159, "ec2.ap-southeast-4.amazonaws.com", false, true);
        String str170 = str159;
        String str171 = str160;
        b(region30, str171, "elasticloadbalancing.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str161, "firehose.ap-southeast-4.amazonaws.com", false, true);
        String str172 = str161;
        String str173 = str162;
        b(region30, str173, "iot.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str163, "kinesis.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str153, "kms.ap-southeast-4.amazonaws.com", false, true);
        String str174 = str153;
        b(region30, str164, "lambda.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str154, "logs.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str144, "polly.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str134, "s3.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "sdb", "sdb.ap-southeast-4.amazonaws.com", false, true);
        b(region30, "sns", "sns.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str7, "sqs.ap-southeast-4.amazonaws.com", false, true);
        b(region30, str53, "sts.ap-southeast-4.amazonaws.com", false, true);
        Region region31 = new Region("il-central-1", str110);
        arrayList8.add(region31);
        b(region31, str165, "autoscaling.il-central-1.amazonaws.com", false, true);
        b(region31, str166, "cognito-identity.il-central-1.amazonaws.com", false, true);
        String str175 = str156;
        b(region31, str175, "cognito-idp.il-central-1.amazonaws.com", false, true);
        b(region31, str167, "cognito-sync.il-central-1.amazonaws.com", false, true);
        String str176 = str167;
        String str177 = str168;
        b(region31, str177, "data.iot.il-central-1.amazonaws.com", false, true);
        b(region31, str169, "dynamodb.il-central-1.amazonaws.com", false, true);
        String str178 = str169;
        String str179 = str170;
        b(region31, str179, "ec2.il-central-1.amazonaws.com", false, true);
        b(region31, str171, "elasticloadbalancing.il-central-1.amazonaws.com", false, true);
        String str180 = str171;
        String str181 = str172;
        b(region31, str181, "firehose.il-central-1.amazonaws.com", false, true);
        b(region31, str173, "iot.il-central-1.amazonaws.com", false, true);
        b(region31, str163, "kinesis.il-central-1.amazonaws.com", false, true);
        String str182 = str163;
        b(region31, str174, "kms.il-central-1.amazonaws.com", false, true);
        b(region31, str164, "lambda.il-central-1.amazonaws.com", false, true);
        b(region31, str154, "logs.il-central-1.amazonaws.com", false, true);
        b(region31, str144, "polly.il-central-1.amazonaws.com", false, true);
        b(region31, str134, "s3.il-central-1.amazonaws.com", false, true);
        b(region31, "sdb", "sdb.il-central-1.amazonaws.com", false, true);
        b(region31, "sns", "sns.il-central-1.amazonaws.com", false, true);
        b(region31, str7, "sqs.il-central-1.amazonaws.com", false, true);
        b(region31, str53, "sts.il-central-1.amazonaws.com", false, true);
        Region region32 = new Region("ca-west-1", str110);
        arrayList8.add(region32);
        b(region32, str165, "autoscaling.ca-west-1.amazonaws.com", false, true);
        b(region32, str166, "cognito-identity.ca-west-1.amazonaws.com", false, true);
        b(region32, str175, "cognito-idp.ca-west-1.amazonaws.com", false, true);
        b(region32, str176, "cognito-sync.ca-west-1.amazonaws.com", false, true);
        b(region32, str177, "data.iot.ca-west-1.amazonaws.com", false, true);
        b(region32, str178, "dynamodb.ca-west-1.amazonaws.com", false, true);
        b(region32, str179, "ec2.ca-west-1.amazonaws.com", false, true);
        b(region32, str180, "elasticloadbalancing.ca-west-1.amazonaws.com", false, true);
        b(region32, str181, "firehose.ca-west-1.amazonaws.com", false, true);
        b(region32, str173, "iot.ca-west-1.amazonaws.com", false, true);
        b(region32, str182, "kinesis.ca-west-1.amazonaws.com", false, true);
        b(region32, str174, "kms.ca-west-1.amazonaws.com", false, true);
        b(region32, str164, "lambda.ca-west-1.amazonaws.com", false, true);
        b(region32, str154, "logs.ca-west-1.amazonaws.com", false, true);
        b(region32, str144, "polly.ca-west-1.amazonaws.com", false, true);
        b(region32, str134, "s3.ca-west-1.amazonaws.com", false, true);
        b(region32, "sdb", "sdb.ca-west-1.amazonaws.com", false, true);
        b(region32, "sns", "sns.ca-west-1.amazonaws.com", false, true);
        b(region32, str7, "sqs.ca-west-1.amazonaws.com", false, true);
        b(region32, str53, "sts.ca-west-1.amazonaws.com", false, true);
        return arrayList8;
    }

    public static void b(Region region, String str, String str2, boolean z11, boolean z12) {
        Map<String, String> h11 = region.h();
        Map<String, Boolean> b11 = region.b();
        Map<String, Boolean> c11 = region.c();
        h11.put(str, str2);
        b11.put(str, Boolean.valueOf(z11));
        c11.put(str, Boolean.valueOf(z12));
    }
}
