package com.tencent.liteav.videobase.videobase;

import com.engagelab.privates.push.constants.MTPushConstants;
import com.sumsub.sns.prooface.network.Liveness3dFaceRepository;
import com.tencent.thumbplayer.tcmedia.api.TPErrorCode;

public enum f {
    STATUS_VIDEO_NONE(0),
    STATUS_VIDEO_CAPTURE_REAL_FRAME_RATE(1),
    STATUS_VIDEO_PREPROCESS_AVERAGE_PROCESS_COST(101),
    STATUS_VIDEO_PREPROCESS_FPS_IN(103),
    STATUS_VIDEO_ENCODE_REAL_ENCODE_BITRATE(201),
    STATUS_VIDEO_ENCODE_REAL_FRAME_RATE(202),
    STATUS_VIDEO_ENCODE_AVERAGE_ENCODE_COST(203),
    STATUS_VIDEO_SW_DECODE_TASK_COST(404),
    STATUS_VIDEO_HW_DECODE_TASK_COST(405),
    STATUS_VIDEO_RENDER_RESOLUTION(502),
    STATUS_VIDEO_CONSUMER_RECEIVE_FPS(700),
    STATUS_VIDEO_DECODER_FRAMERATE(804),
    STATUS_VIDEO_DECODER_ERROR(805),
    STATUS_VIDEO_CAPTURE_FRAME(1000),
    STATUS_VIDEO_INCOME_FRAME(1001),
    STATUS_VIDEO_CAMERA_START_COST(1002),
    STATUS_VIDEO_CAMERA_START_ERROR_TYPE(1003),
    STATUS_VIDEO_PREPROCESS_TIME(2000),
    STATUS_VIDEO_PREPROCESS_BEAUTY_SETTINGS(2001),
    STATUS_VIDEO_CUSTOM_PREPROCESS_AVERAGE_COST(2002),
    STATUS_VIDEO_ENCODER_TYPE(3000),
    STATUS_VIDEO_ENCODER_FRAME(3001),
    STATUS_VIDEO_ENCODER_COST(3004),
    STATUS_VIDEO_ENCODER_CODEC(3005),
    STATUS_VIDEO_ENCODER_ABILITY(3006),
    STATUS_VIDEO_HW_ENCODE_START_ERROR_TYPE(MTPushConstants.PlatformNode.CODE_UPLOAD_TOKEN_SUCCESS),
    STATUS_VIDEO_ENCODE_TASK_COST(MTPushConstants.PlatformNode.CODE_GET_TOKEN_SUCCESS),
    STATUS_VIDEO_DECODER_TYPE(TPErrorCode.TP_ERROR_TYPE_DOWNLOAD_PROXY),
    STATUS_VIDEO_DECODER_FRAME(Liveness3dFaceRepository.f40233m),
    STATUS_VIDEO_DECODER_COST(4004),
    STATUS_VIDEO_DECODER_CACHE(4005),
    STATUS_VIDEO_DECODER_CODEC(4006),
    STATUS_VIDEO_DECODER_CODEC_COST(4007),
    STATUS_VIDEO_HW_DECODE_START_ERROR_TYPE(4008),
    STATUS_VIDEO_DECODE_TASK_COST(4009),
    STATUS_VIDEO_RENDER_FRAME(5000),
    STATUS_VIDEO_RECEIVED_FRAME(6000),
    STATUS_VIDEO_DROP_FRAME(6001),
    STATUS_CONSUMER_FINISH_HANDLE_FRAME(6002);
    
    private static final f[] N = null;
    private final int value;

    /* access modifiers changed from: public */
    static {
        N = values();
    }

    private f(int i11) {
        this.value = i11;
    }
}
